package org.seckill.entity;

import java.util.Date;

public class SuccessSeckill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_seckill.seckill_id
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    private Long seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_seckill.user_phone
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    private Long userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_seckill.state
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_seckill.create_time
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_seckill.seckill_id
     *
     * @return the value of success_seckill.seckill_id
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_seckill.seckill_id
     *
     * @param seckillId the value for success_seckill.seckill_id
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_seckill.user_phone
     *
     * @return the value of success_seckill.user_phone
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    public Long getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_seckill.user_phone
     *
     * @param userPhone the value for success_seckill.user_phone
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    public void setUserPhone(Long userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_seckill.state
     *
     * @return the value of success_seckill.state
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_seckill.state
     *
     * @param state the value for success_seckill.state
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_seckill.create_time
     *
     * @return the value of success_seckill.create_time
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_seckill.create_time
     *
     * @param createTime the value for success_seckill.create_time
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}