package org.seckill.dao;

import java.util.List;
import org.seckill.entity.Seckill;

public interface SeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    int deleteByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    int insert(Seckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    Seckill selectByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    List<Seckill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    int updateByPrimaryKey(Seckill record);
}