package org.seckill.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.seckill.entity.SuccessSeckill;

public interface SuccessSeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    int deleteByPrimaryKey(@Param("seckillId") Long seckillId, @Param("userPhone") Long userPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    int insert(SuccessSeckill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    SuccessSeckill selectByPrimaryKey(@Param("seckillId") Long seckillId, @Param("userPhone") Long userPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    List<SuccessSeckill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_seckill
     *
     * @mbggenerated Wed May 29 16:03:39 CST 2019
     */
    int updateByPrimaryKey(SuccessSeckill record);
}